# This is a basic workflow to help you get started with Actions

name: Jacoco Coverage

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build coverage report
        run: ./gradlew build jacocoTestReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/customJacocoReportDir/test/jacocoTestReport.xml
          fail_ci_if_error: true
